# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SenseTime_OVI_TestTool.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from SenseTime_UI_child_SSH_settings import Ui_Child_SSH_settings

class DialogWindow(QtWidgets.QMainWindow, Ui_Child_SSH_settings):
    def __init__(self, parent=None):
        super(DialogWindow, self).__init__(parent)
        self.setupUi(self)

    def update_progressbar(self, p_int):
        self.progressBar.setValue(p_int)  # 更新进度条